### ISSUE TITLE
Origin and licenses issues

### ISSUE THREAD

**Issue by pombredanne** [jazzband/tablib#114]
While tablib is MIT-licensed, there are several potential provenance and license issues with Oo, XLS and XLSX formats that tablib embeds. I have collected some of these potential issues here. This is at best ... byzantine. 

It feels a tad overwhelming: I am just raising the issue and I would like to help to fix this.

There are some things to consider with regards to implementations of Excel formats read and write (in xlrt, xlwt and openpyxl) as there may be issues with components that support XLS or XLSX formats in general.

See the discussion on these:
- https://github.com/python-excel/xlrd/issues/32
- https://github.com/Niggler/js-xls/issues/1
- https://github.com/stephen-hardy/xlsx.js/issues/8
- https://github.com/stephen-hardy/xlsx.js/blob/master/LICENSE.txt

See also Apache guidelines for POI: http://poi.apache.org/guidelines.html
## openpxyl

https://bitbucket.org/ericgazoni/openpyxl/ is reported as being derived from PHPExcel which is LGPL-licensed at https://github.com/PHPOffice/PHPExcel but openpyxl is not LGPL but MIT-licensed.  If this is really derived then there is a possible issue as the license may be that of the original not of the derivative.  It also contains code from other origins such as http://lethain.com/entry/2009/jan/22/handling-very-large-csv-and-xml-files-in-python/ 
 PHPExcel in turns claims to contain code from these origins:
- PEAR::SpreadsheetExcelWriter (http://pear.php.net/package/Spreadsheet_Excel_Writer also LGPL
- JavaScript Excel Formula Parser (http://ewbi.blogs.com/develops/2007/03/excel_formula_p.html )
- PHP-ExcelReader (http://sourceforge.net/projects/phpexcelreader itself also based on http://www.andykhan.com/excelread/ or jexcelapi see below )
- FPDF (http://www.fpdf.org/) (probably not relevant here)
- TCPDF (http://www.tcpdf.org/) (probably not relevant here)
- PHP port of polyfit (http://www.phpmath.com/home?op=cat&cid=17) (probably not relevant here)
- PHP port of JAMA matrix library (http://www.phpmath.com/build03/JAMA/docs/) (probably not relevant here)
## XLRD

 Uses a combo of a BSD license and a BSD original license. XLRD itself is based on a BSD-original-licensed component written in C called xlreader at http://www.giffin.org/xlreader.php released circa fall 2001. This is turn is based on a LGPL 2.0-licensed component at http://www.andykhan.com/excelread/ released circa fall 2001 at  http://web.archive.org/web/20011117133717/http://www.andykhan.com/excelread/ . ExcelRead later became jExcelAPI http://jexcelapi.sourceforge.net/, still LGPL-licensed. 

The xlrd license history is confusing at best, because if the C xlreader is really a derivative of the Java LGPL-licensed excelread, then its BSD original license might be moot, as the license may be that of the original not of the derivative.  If this was just used for ideas, then only the BSD original license issue may stand (with its extensive advertising clause being an issue and making it not GPL-compatible among other things and a pain with MIT or Apache-licensed code).
## XLWT

 Uses a combo of bsd-modified and bsd-original-license at https://github.com/python-excel/xlwt/blob/master/licences.py . It started as a fork of PyExcelerator by Roman V. Kiseliov that was also BSD-original at http://sourceforge.net/projects/pyexcelerator/ .  Pyexcelerator in turn has this notice: http://ftp-master.metadata.debian.org/changelogs//main/p/pyexcelerator/pyexcelerator_0.6.4.1-1_copyright .  And per https://github.com/python-excel/xlwt/commit/be268c8a01f1738c39aa3486802972ae6c7f34d1 and  https://github.com/python-excel/xlwt/blob/master/licences.py ... this is a partial port of pyXLWriter http://pyxlwriter.sourceforge.net/ LGPL-2.0-licensed, but itself claiming to be a port of a Perl module by John McNamara (Perl Spreadsheet::WriteExcel which was Perl-licensed.)

The combo of BSD, BSD original, Perl and LGPL may not mesh well. The Perl issue may have been addressed here:  https://launchpad.net/ubuntu/raring/+source/xlwt/+copyright
## Other components:
- **ODF/OpenOffice** : this is LGPL-licensed. The license text is missing.
- **omnijson** : has code derived from simplejson and notice/license text is missing; it also includes ordereddict from Raymond Hettinger.
- **unicodecsv** (v0.8.0) from https://pypi.python.org/pypi/unicodecsv/  https://github.com/jdunck/python-unicodecsv is BSD-licensed and the notice is missing
- **PyYAML** : '3.09' from http://pyyaml.org/download/pyyaml/PyYAML-3.09.tar.gz is MIT licensed and the notice/license is missing
- **markup** is from http://markup.sourceforge.net/ is Public Domain

See also: http://ftp-master.metadata.debian.org/changelogs//main/p/python-tablib/python-tablib_0.9.11-1_copyright

**Comment by amcgregor** [comment]
Forced to remove tablib from project due to viral licenses.  @kennethreitz You might not care, but this does represent a continuing problem, years later.

**Comment by MalinaliRap** [comment]
how do I find practical examples of Worksheet cell styling?
