### ISSUE TITLE
tsv - importing tab delimited text files 

### ISSUE THREAD

**Issue by MLib** [jazzband/tablib#140]
When using tablib  (dependency of django-import-export) to import tab delimited text files (from excel),  I get the following error 

new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

The problem is solved when I change _tsv.py:

``` python
# if is_py3:
#     rows = csv.reader(in_stream.split('\r\n'), delimiter='\t')
# else:
#     rows = csv.reader(in_stream.split('\r\n'), delimiter='\t',
#                       encoding=DEFAULT_ENCODING)
if is_py3:
    rows = csv.reader(in_stream.split('\n'), delimiter='\t')
else:
    rows = csv.reader(in_stream.split('\n'), delimiter='\t',
                      encoding=DEFAULT_ENCODING)
```

I tested on linux server, both osx and Windows clients now OK
I tested on osx server, both osx and Windows clients now OK

**Comment by hugovk** [comment]
The `_tsv.py` file has changed quite a bit since this was reported, and all tests now pass on macOS, Windows and Linux (eg. see https://github.com/jazzband/tablib/pull/409).

Closing, please comment or open a new issue if there's still a problem.
