### ISSUE TITLE
Use import_set

### ISSUE THREAD

**Issue by mazing** [jazzband/tablib#166]
It seems it's not documented how to import a file and loop through the rows and columns.

Can someone help me out with a small example?

In the API the function import_set() is listed, but I don't know how to use this function.

**Comment by vyscond** [comment]
i've tried the ```open().read()``` but only return __None__ object from the ```tablib.import_set()```. I'm pretty sure the filepath is correct because i can read the whole content of the file with ```"".join(open("path"))```.

```python

            csvfiles = glob.glob( 'backup_db/{date}/*.csv'.format( date=args[0] ) ) # args[0] = '2015_05_02' (like year, month, day)

            for csvf in csvfiles : # csvf = 'backup_db/2015_05_02/SomeModel.csv'

                #print( 'importing ' , csvf , '\n' , ''.join(open(csvf,'r')) )

                dataset = tablib.import_set( open(csvf,'r').read() )
                
                print( 'dataset -> ' , dataset ) # None

                modelname = os.path.basename(csvf)[:-4]
                
                print( modelname+'Resource' )

                model = getattr(admin,modelname+'Resource')()

                print(dataset)

                model.import_data(dataset=dataset,dry_run=True) # Error - > 'NoneType' object has no attribute 'dict'

```

**Comment by flacostec** [comment]
Same issue. 
```
>>> import tablib
>>> print tablib.import_set(open("derp.xls", "rb"))
None
```
File is existing

**Comment by casimir** [comment]
Just encountered this issue with a CSV file. When using `;` as separator `tablib.import_set` return `None`, whereas when using `,` it return the correct dataset.

**Comment by claudep** [comment]
Please reopen if you still have issues on the latest release.
