### ISSUE TITLE
Install compilation errors on Python 3.4

### ISSUE THREAD

**Issue by pwalsh** [jazzband/tablib#178]
- Python 3.4
- pip install tablib

On install, a series of compile errors. For example:

```
*** Error compiling '{MYPATH}/build/tablib/tablib/packages/markup.py'...
  File "{MYPATH}/build/tablib/tablib/packages/markup.py", line 186
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax
```

After that tablib does seems to work of course, as all the errors come from code that specifically targets py2. Still, it is confusing/undesirable.

**Comment by sametmax** [comment]
+1

**Comment by franciscod** [comment]
same happened. very confusing at least

**Comment by peterfarrell** [comment]
+1 - happened to us today and we went down the rabbit hole of wondering if TabLib has support for Py3.

**Comment by andriisoldatenko** [comment]
we can close this ticket because now we support not python 3.4
More info at 
[envlist = py26, py27, py32, py33, py34, py35, py36, pypy](https://github.com/kennethreitz/tablib/blob/master/tox.ini#L7)
