### ISSUE TITLE
Tablib import Excel NA() values as 42

### ISSUE THREAD

**Issue by rhunwicks** [jazzband/tablib#202]
If you import an xls or xlsx file into a dataset using `import_set` or `import_sheet` and one of the cells contains a `NA()` error value then the value of the imported cell in the dataset is 42.

That's probably not what you want in any circumstance.

See http://stackoverflow.com/questions/4928629/xlrd-excel-script-converting-n-a-to-42, for example.

You can work around that by changing:

```python
row_vals = [c.value for c in row]
```

to

```python
row_vals = [xlrd.error_text_from_code[c.value] if c.ctype == xlrd.XL_CELL_ERROR else c.value for c in row]
```

**Comment by kennethreitz** [comment]
@rhunwicks can you send a pull request?

**Comment by rhunwicks** [comment]
I'm trying to write a test to make sure I can detect the error.

```
from tablib.compat import openpyxl, BytesIO

    def test_xlsx_import_set(self):
        """Generate and import XLSX set serialization."""
        data.append(self.john)
        data.append(self.george)
        data.headers = self.headers
        expected = data.dict

        wb = openpyxl.workbook.Workbook()
        ws = wb.worksheets[0]
        ws.append(self.headers)
        ws.append(self.john)
        ws.append(self.george)
        xlsx = BytesIO()
        wb.save(xlsx)
        data.xlsx = xlsx.getvalue()
        self.assertEqual(data.dict, expected)
```

This runs fine on Python 2.7, but on 3.4 it gives:

```
    def _get_xml_iter(xml_source):
    
        if not hasattr(xml_source, 'name'):
>           return StringIO(xml_source)
E           TypeError: initial_value must be str or None, not bytes
```

presumably because of Python3 unicode handling.

**Comment by hugovk** [comment]
Cannot reproduce with Python 3.5-3.8, see https://github.com/jazzband/tablib/pull/414.
