### ISSUE TITLE
error with reading xlsx file

### ISSUE THREAD

**Issue by jayzh1010** [jazzband/tablib#230]
`xlsx.detect` use `openpyxl.reader.excel.load_workbook(stream)` to decide whether this file format is xlsx.

But actually, the `openpyxl.reader.excel.load_workbook()` use filename for the args, but not the file content.

**Comment by Xuefeng-Zhu** [comment]
stream is fileobject, which can be handled by openpyxl.reader.excel.load_workbook

**Comment by claudep** [comment]
Fixed by 91062672b5406972da75bdcf02ad8373fff96377
