### ISSUE TITLE
HTML input

### ISSUE THREAD

**Issue by klothe** [jazzband/tablib#243]
I have an application that needs to import HTML tables, and already uses Tablib for some other data formats. I noticed that Tablib supports HTML tables as an output format only. (https://github.com/kennethreitz/tablib/blob/master/tablib/formats/_html.py)

Is there any interest in adding HTML as an input format?

If this were implemented with an HTML parsing library such as BeautifulSoup, would a copy of that library have to be added to tablib/packages?

**Comment by turicas** [comment]
@klothe, you may want to use the library [rows](https://github.com/turicas/rows) for this kind of task. :)

**Comment by klothe** [comment]
@turicas thanks, that would be a good option if I didn't have a lot of code written on top of Tablib already.

I'll go ahead and add HTML input unless anyone objects.
