### ISSUE TITLE
Quoted CSV is not respected

### ISSUE THREAD

**Issue by acjackman** [jazzband/tablib#250]
Using table to try and import the following CSV string, Tablib fails with an `UnsupportedFormat` exception when using a comma inside of a quoted string in a CSV.

``` python
from tablib import Dataset

without_comma = '''number,name
contract3,"Reinger Altenwerth and Willms"
contract4,Wyman-Ferry
'''
Dataset().load(without_comma)

with_comma = '''number,name
contract3,"Reinger, Altenwerth and Willms"
contract4,Wyman-Ferry
'''
Dataset().load(with_comma)
```

**Comment by int-ua** [comment]
Can you please rename the issue to something like "Failure to recognise CSV format with comma inside quotes"? Current title is misleading, I thought it was about exporting data.

**Comment by claudep** [comment]
I just added a test that currently passes. Should have been fixed in the meantime.
