### ISSUE TITLE
Import .xlsx Databook

### ISSUE THREAD

**Issue by Universemul** [jazzband/tablib#274]
I'm trying to import a xlsx file into a Databook (you can see the file below).
This file has multiple sheets.

Right now, the only solution is to split my .xlsx into multiple csv or xls, and import inside a Databook

Is there a way to import this file directly with a Databook?

[test2.xlsx](https://github.com/kennethreitz/tablib/files/745196/test2.xlsx)

**Comment by maltalk** [comment]
A while ago i was trying to import using import_book but now working.
Try with:
`Databook().load('xlsx', file.read())`
Since #315 is still open.
