### ISSUE TITLE
UnsupportedFormat raised when trying to load YAML file

### ISSUE THREAD

**Issue by luciocorrea** [jazzband/tablib#285]
Hi guys. 

I'm  trying to import  YAML files into a Dataset, but it always raises an UnsupportedFormat. That's the code I'm using:

import tablib
dataset = tablib.Dataset().load(open('Radial-pedra-br.yml').read())

I used PyYAML to import the same file and it worked fine:

import yaml
mported_data = yaml.safe_load(open('Radial-pedra-br.yml'))

Link to the YAML file: https://pastebin.com/Vh0G1Dc5

Thanks in advance..

**Comment by claudep** [comment]
Your YAML content is not valid. You can see that by providing the format parameter to `load()` to force using the YAML format:
```
dataset = tablib.Dataset().load(open('Radial-pedra-br.yml').read(), 'yaml')

...traceback...
ParserError: while parsing a block node
expected the node content, but found '?'
  in "<unicode string>", line 20, column 9:
            Tipo: "Zircônia"
            ^
```
