### ISSUE TITLE
Phone numbers and similar treated as numbers in XLSX export

### ISSUE THREAD

**Issue by defeo** [jazzband/tablib#288]
When textual data contains, e.g., phone numbers such as "0123456", these are exported as integers in XLSX format, thus making the 0 disappear in Excel, or, worse, showing them in scientific notation.

Here's an example:

```
tablib.Dataset(('a',10,'010'), headers=('A', 'B', 'C'))
```

This is exported correctly in XLS format, but wrongly in XLSX.

**Comment by kennethreitz** [comment]
Pull requests accepted!

**Comment by defeo** [comment]
I have no idea how the XLSX format works. I am afraid I will not have time to dig this and make a PR anytime soon.

**Comment by kennethreitz** [comment]
It's pretty simple, the codebase! https://github.com/kennethreitz/tablib/blob/master/tablib/formats/_xlsx.py#L36

**Comment by claudep** [comment]
I was not able to reproduce on master, but I still added a test related to your issue (which cannot test how the real Excel program interpret the value, of course!)
