### ISSUE TITLE
Unpickled Dataset results in unusable CSV and JSON exports

### ISSUE THREAD

**Issue by woozyking** [jazzband/tablib#293]
```TypeError: <csv/json and probably more>() takes 0 positional arguments but 1 was given```

This happens after unpickling a pickled `Dataset` instance. More specifically, the pickling/unpickling process is through `rq` (http://python-rq.org/)

`.dict` would still work, and direct `repr/str` of the Dataset instance would still work.

**Comment by claudep** [comment]
I created a basic test to see if pickling was somewhere broken. Either I didn't reproduce the exact conditions you had or the issue has been solved by some other recent commit. If you still care for this, could you check it?

**Comment by woozyking** [comment]
Apologies as this has been a bit too far back to recall on the exact issue. I think it's fairly safe to assume this is no longer an issue as I also could not reproduce it now.

Closing.
