### ISSUE TITLE
XLSX export with separators fails on 0.11.5

### ISSUE THREAD

**Issue by mpasternak** [jazzband/tablib#304]
tablib 0.11.5 with Python 3.6

When trying to export XLSX file (not XLS) with separators, I get the following error:

```
Traceback (most recent call last):
  File "test2.py", line 11, in <module>
    x.write(data.xlsx)
  File "/Users/mpasternak/envs/django-flexible-reports/lib/python3.6/site-packages/tablib/formats/_xlsx.py", line 43, in export_set
    dset_sheet(dataset, ws, freeze_panes=freeze_panes)
  File "/Users/mpasternak/envs/django-flexible-reports/lib/python3.6/site-packages/tablib/formats/_xlsx.py", line 135, in dset_sheet
    cell.value = unicode('%s' % col, errors='ignore')
TypeError: decoding str is not supported
```

Minimal non-working code example:

```
import tablib

data = tablib.Dataset()

for a in range(5):
    data.append_separator('foobar')
    for a in range(10):
        data.append(["asdf", "asdf", "asdf"])

x = open("test2.xlsx", "wb")
x.write(data.xlsx)
x.close()
```

Docs say that separators are supported only for MS Excel but they don't precise which one. XLS works with separators. XLSX does not. From the exception, I see that it would not be that hard to implement. Unless I'm doing something wrong. If you give me a few hints on how this should be fixed, I can prepare a problem report.

**Comment by claudep** [comment]
Thanks for providing the code example. I could not reproduce on master but I still added tests to confirm that.
