### ISSUE TITLE
xlsx casting all types to string | unicode

### ISSUE THREAD

**Issue by nakashu** [jazzband/tablib#314]
```python
head = ('integer', 'float', 'text', 'integer as text')
data = [(123, 3.14, 'hello world', '987',),]
data = tablib.Dataset(*data, headers=head)
f = open('types.xlsx', 'wb')
f.write(data.xlsx) # works correctly with data.xls
```

**Expected behaviour:**

Exported file would have values in the same type as defined above.
Eg. integer => integer,  float => float, string => string

**What is happening**

All types are casted to strings
integer => string,  float => string, string => string

This is a problem when people what to do some counting operation with the resulting `xlsx` as it will break, and needs to be changed inside the document.

**Where and when is the origin**

* Introduced in `version  0.11.5` in [commit](https://github.com/kennethreitz/tablib/pull/221/files#diff-e084e40878a6d2614b831e70c87fb140R142) by adding unicode() around `col`
* imho a silent BC, as it changes functionality

Internally unicode function return a string object, or for python3 compatibility is casted to string object:
```python
# inside compat.py
if is_py3:
    unicode = str;
```

**Fix**

Leave handling of types for `openpyxl` and remove unicode wraps around values.

This fix was proposed and merged already in #309, but it was done again develop branch that is quite outdated and not compatible with python3.
Also when exporting to `xls` it works correctly as unicode wrapping wasn't added here.

**Comment by timtan** [comment]
any plan for the fix?
