### ISSUE TITLE
how to name a xls's datasheet when adding a dataset to a databook?

### ISSUE THREAD

**Issue by nasoundead** [jazzband/tablib#319]
```python
databook = tablib.Databook()
data_set1 = tablib.Dataset(headers=headers)
data_set2 = tablib.Dataset(headers=headers)
...
databook.add_sheet(data_set1)
databook.add_sheet(data_set2)
 with open("xxx.xls", "wb") as f:
        f.write(databook.xls)
```
![image](https://user-images.githubusercontent.com/13186459/34189795-352fe5d2-e578-11e7-9693-0b645b98bb73.png)

**Comment by yujinyuz** [comment]
I also wanted to know whether this has a solution. I tried this one http://docs.python-tablib.org/en/master/tutorial/#separators

And the sheet name I'm getting is `Tablib Dataset`

**Comment by jslopez** [comment]
Each dataset has the `title` attribute: `data_set1.title = 'data set 1'`

**Comment by hugovk** [comment]
Confirmed with latest Tablib 0.14 on Python 3.7:

```python
import tablib

headers = [1, 2, 3]
databook = tablib.Databook()
data_set1 = tablib.Dataset(headers=headers)
data_set2 = tablib.Dataset(headers=headers)

# Add sheet names
data_set1.title = "data set 1"
data_set2.title = "data set 2"

databook.add_sheet(data_set1)
databook.add_sheet(data_set2)
with open("xxx.xls", "wb") as f:
       f.write(databook.xls)
```

![image](https://user-images.githubusercontent.com/1324225/67299517-72b2dc00-f4f5-11e9-856c-e810ef829d5c.png)
