### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by 978740431** [jazzband/tablib#320]
when I import tablib happened 
<img width="711" alt="error" src="https://user-images.githubusercontent.com/11803404/34649796-bbccd718-f3f0-11e7-9ddf-9ca742fb15dc.png">
ValueError: zero length field name in format
I use 6.9 centos
2.6.6 python
tablib is latest version
I use pip install tablib to install tablib

**Comment by claudep** [comment]
Should probably be fixed in recent versions. The stack strace also seems to indicate the issue is in the odf package, not in tablib.
