### ISSUE TITLE
export "cli" format

### ISSUE THREAD

**Issue by nskalis** [jazzband/tablib#340]
Hi,

Would you consider an `export` format suited for cli purposes as well, like

1. the `simple` table format as described here https://pypi.org/project/tabulate/
2. the same format is used by all tools from HashiCorp, Consul, Vault, etc.

in other words, it is a familiar more or less format.

Example:
```
Path          Type         Description
----          ----         -----------
cubbyhole/    cubbyhole    per-token private secret storage
kv/           kv           n/a
secret/       kv           key/value secret storage
sys/          system       system endpoints used for control, policy and debugging
```

**Comment by xdanielsb** [comment]
Hi @nskalis 

now I am taking care of this feature, sorry for the delay

**Comment by claudep** [comment]
@xdanielsb You are welcome to work on this, but note that we won't commit anything before #256 is reviewed and pushed.

**Comment by xdanielsb** [comment]
Hi @nskalis 

Here you can find a tutorial, whereas the pull request is approved you can use this not official feature in the branch feature-cli-format in the following way,

```python
students = tb.Dataset()
students.headers = ['first', 'last']
students.rpush(['Kenneth', 'Reitz'], tags=['male', 'technical'])
students.rpush(['Daniel', 'Dupont'], tags=['male', 'creative'])
students.rpush(['Bessie', 'Monke'], tags=['female', 'creative'])

print( students.export('cli',tablefmt="github") )
```
| first   | last   |
|---------|--------|
| Kenneth | Reitz  |
| Daniel  | Dupont |
| Bessie  | Monke  |

It's that simple, you can use all formats that [tabulate](https://pypi.org/project/tabulate/) offers

**Comment by claudep** [comment]
The commit was reverted.

**Comment by claudep** [comment]
This functionality was pushed in fa30ea858d0ac41f2f542e0c50d9f9a2e343deb2
