### ISSUE TITLE
version 0.13.0 fails to install with pip

### ISSUE THREAD

**Issue by nagado** [jazzband/tablib#355]
https://github.com/kennethreitz/tablib/blob/733d77ad1ed393869825f74803781d9b9873782e/setup.py#L38

Could not find a version that satisfies the requirement backports.csv (from tablib ....)

**Comment by claudep** [comment]
Moreover I think backports.csv should only be conditionally added to install_requires when running setup.py on Python 2.

**Comment by claudep** [comment]
Should be fixed by c136940801cd
