### ISSUE TITLE
CSV header

### ISSUE THREAD

**Issue by hpbrewton** [jazzband/tablib#367]
# CSV Header First Row

Per the documentation, it seems there is no option to opt out of using first row as headers (yet). Is this still accurate?

**Comment by jieter** [comment]
That's correct. I did push a commit adding a way to override the `TableExport` class on the view, and moved some code which use to live in `TableExport.__init__` to a [new method `TableExport.table_to_dataset`.](https://github.com/jieter/django-tables2/pull/677/files#diff-170a684f7bf78c969aeb146189e3dbb9L50).

It should now be fairly easy to override use a custom `TableExport`:

```python
class HeaderlessTableExport(TableExport):
def table_to_dataset(self, table, exclude_columns):
        dataset = Dataset()
        for i, row in enumerate(table.as_values(exclude_columns=exclude_columns)):
            if i > 0:
               dataset.append(row)
        return dataset
```

Note that this is not yet released or merged in master.

**Comment by xdanielsb** [comment]
Hi @hpbrewton 

please find below some ways for not using the first row as headers,

#### sending the arg (hearders = False)
```python
#way one
import_set(open('data.csv').read(), headers = False)
#way two
Dataset().load(open('data.csv').read(), headers=False)
```
