### ISSUE TITLE
version 0.13.0 csv.export('csv', delimiter=";") fails

### ISSUE THREAD

**Issue by johanwinter1** [jazzband/tablib#369]
I use tablib to generate csv with delimiter ;

```python
csv.export('csv', delimiter=";")
```

after upgrading to version 0.13.0 it throws a Type error.

```
"delimiter" must be string, not bytes
```

**Comment by claudep** [comment]
I guess you are using Python 2. I'm not sure we'll invest much time in that issue as Python 2 is EOL in 3 months...

**Comment by hugovk** [comment]
Closing, current master only supports Python 3. I recommend upgrading to Python 3.
