### ISSUE TITLE
Site seems to be offline

### ISSUE THREAD

**Issue by sidneijp** [jazzband/tablib#377]
http://docs.python-tablib.org

**Comment by claudep** [comment]
@vinayak-mehta Any hint about that domaine name? Should be simply use readthedocs?

**Comment by vinayak-mehta** [comment]
I think Kenneth still owns the domain name, we can totally go for readthdocs!

**Comment by vinayak-mehta** [comment]
I'm not sure if readthedocs supports org accounts or if jazzband already has a readthedocs account. You can set up the docs on your own readthedocs or I can also do that, whichever you prefer @claudep.

**Comment by jezdez** [comment]
With the close of #378 we've moved to ReadTheDocs: https://tablib.readthedocs.io/

Jazzband doesn't currently support own domains for maintenance reasons (financial and organization-wise). Apologies for the inconvenience.
