### ISSUE TITLE
Merge develop and master branch

### ISSUE THREAD

**Issue by claudep** [jazzband/tablib#380]
We plan to remove the develop branch at some point. We should compare the branches and possibly merge to master some develop commits which have not been integrated until now.

**Comment by hugovk** [comment]
Looking at the network graph https://github.com/jazzband/tablib/network, I _think_ these are the only ones missing from `master`:

* https://github.com/jazzband/tablib/pull/302
* https://github.com/jazzband/tablib/pull/309
* https://github.com/jazzband/tablib/pull/315

**Comment by hugovk** [comment]
PR https://github.com/jazzband/tablib/pull/383 cherry picks the commits from #302 and #315.

I've not done #309 because it conflicts.

**Comment by claudep** [comment]
For #309, I suggest the PR #386.

**Comment by claudep** [comment]
I think all the code is now in master. I'm not sure if we should delete it or keep it a while for history purposes.
