### ISSUE TITLE
Delete Pipfile.lock?

### ISSUE THREAD

**Issue by claudep** [jazzband/tablib#388]
I understand the merits of committing a Pipfile.lock file is subject to debate, but as almost all our dependencies are now unpin, I don't see a good reason to keep it.
@jdufresne, any input?

**Comment by jdufresne** [comment]
I agree.

My personal preference usually comes down to:

Enduser applications: Lock dependencies.
Reusable libraries: Keep unlocked to allow for testing and using a range of versions.

**Comment by claudep** [comment]
Thanks Jon for this confirmation.
