### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by hugovk** [jazzband/tablib#390]
Python 2 reaches end-of-life on **2020-01-01**.

See https://python3statement.org for a list of projects which have pledged to drop support for Python 2 on or before its EOL.

I'd like to suggest making a release soonish with the recent changes that still supports Python 2.7, and then drop it.

That'll allow newer features of Python to be used, and also some vendored code  can be removed (eg. https://github.com/jazzband/tablib/pull/362#issuecomment-538104111) and deal with some other issues (eg. https://github.com/jazzband/tablib/pull/268#issuecomment-473651820).

**Comment by claudep** [comment]
+1. What would you suggest for the next version numbering, 0.13.1?

**Comment by hugovk** [comment]
I don't know the version scheme being used so far, but if we look at the popular [SemVer](https://semver.org):

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
>
> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

...

> **How do I know when to release 1.0.0?**
>
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

Tablib was downloaded nearly 300,000 times last month, I think it's about time for 1.0.0 :)

**Comment by claudep** [comment]
I'm not very comfortable releasing 1.0.0 right now, I'd rather stick with 0.13.1 or 0.14.0 and release 1.0.0 after dropping Python 2. Thoughts?

**Comment by hugovk** [comment]
Agreed. (I mixed up the *next* release with the drop release.)

SemVer says:

* For 0.y.z releases, anything goes.

* For 1+.y.z releases, bump the patch number x.y.Z when there's bugfixes.

* For 1+.y.z releases, bump the minor number x.Y.z when there's new features (and optionally also bugfixes).

I'd probably go for 0.14.0.

**Comment by peymanslh** [comment]
Hello @hugovk @claudep 
Can I work on this issue and send a pull request?

**Comment by claudep** [comment]
Fine for me. It will probably need some rebasing at the time we're ready to commit it.

**Comment by peymanslh** [comment]
I sent a pr: #394 
@claudep

**Comment by claudep** [comment]
PR #394 was merged "manually".
