### ISSUE TITLE
Release 0.14.0

### ISSUE THREAD

**Issue by claudep** [jazzband/tablib#400]
@hugovk Can you check the current code (and HISTORY) and tell me if you think we could release 0.14.0 now? I'd just like to add that the 0.14.x series will be the last supporting Python 2. Would you like to lead the release process?

**Comment by jezdez** [comment]
If I may, I'd like to suggest to calling it `1.0` so tablib can stop using [ZeroVer](https://0ver.org/) 😬

**Comment by claudep** [comment]
My plan was to use 1.0 on the Python 3-only version (that should follow 0.14.0 rather soon), but I'm open to discussion!

**Comment by jezdez** [comment]
Oh right, that works, too. I don't mind either way.

**Comment by hugovk** [comment]
Yep, will release this weekend. Here's a start: https://github.com/jazzband/tablib/pull/402.

As discussed in https://github.com/jazzband/tablib/issues/390, let's go for 0.14.0 for this one, and then onwards and upwards with 1.0 when dropping 2.7!

**Comment by hugovk** [comment]
Updated release notes merged (https://github.com/jazzband/tablib/pull/402). Will now add and push a tag, and we can check the release on Jazzband:

> When you’re ready to do a release to PyPI simply make sure to prepare all the code you’d like just as before (e.g. update `AUTHORS`, `CHANGELOG`, documentation, etc.), commit the changes, tag them with `git tag` and push the code to GitHub with `git push --tags`.
>
> If all goes according to plan, Travis CI will run the test suite for the pushed tag, create release files, uploads it to the Jazzband site, for the lead members or roadies to review. They will be able to confirm the uploads and release them to PyPI individually.

https://jazzband.co/about/releases

**Comment by hugovk** [comment]
The CI successfully built and uploaded the two distributions:

* https://travis-ci.org/jazzband/tablib/jobs/600006208#L777

> There are currently 2 uploads for tablib, with 2 unreleased.

> Multiple uploads for version 0.14.0 found!
> Please make sure you release all uploads individually below.

> File name tablib-0.14.0-py3-none-any.whl

> File name tablib-0.14.0.tar.gz

https://jazzband.co/projects/tablib

I downloaded the files, and can install the wheel fine with pip. Contents of the tar.gz looks good.

Will click the release buttons for each.

**Comment by hugovk** [comment]
Tablib 0.14.0 is released!

https://pypi.org/project/tablib/0.14.0/

```console
$ pip install tablib
Collecting tablib
  Downloading https://files.pythonhosted.org/packages/7f/8d/665f895e4355f1ee95665e003b994512c8b670148a921aa9acec9d1607fb/tablib-0.14.0-py3-none-any.whl (65kB)
     |████████████████████████████████| 71kB 993kB/s
Requirement already satisfied: openpyxl>=2.4.0 in /usr/local/lib/python3.7/site-packages (from tablib) (3.0.0)
Requirement already satisfied: markuppy in /usr/local/lib/python3.7/site-packages (from tablib) (1.14)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from tablib) (3.13)
Requirement already satisfied: xlwt in /usr/local/lib/python3.7/site-packages (from tablib) (1.3.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/site-packages (from tablib) (1.2.0)
Requirement already satisfied: odfpy in /usr/local/lib/python3.7/site-packages (from tablib) (1.4.0)
Requirement already satisfied: jdcal in /usr/local/lib/python3.7/site-packages (from openpyxl>=2.4.0->tablib) (1.4.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/site-packages (from openpyxl>=2.4.0->tablib) (1.0.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/site-packages (from odfpy->tablib) (0.6.0)
Installing collected packages: tablib
Successfully installed tablib-0.14.0
```
Thanks everyone who contributed!

**Comment by claudep** [comment]
hurray \o/
