### ISSUE TITLE
Deprecate the TSV format

### ISSUE THREAD

**Issue by claudep** [jazzband/tablib#432]
In the light of #431, I don't see the utility of a TSV format, as the CSV format can be used to import and export TSV data (as well as many other variation of xSV formats). I would suggest to deprecate it.

**Comment by hugovk** [comment]
Hmm, whilst TSV can indeed be dealt with as CSV with a tab delimiter, TSV is a [well-known format](https://en.wikipedia.org/wiki/Tab-separated_values) so I think it's a useful shortcut for users.

Is it so the only code we need to explicitly support TSV is this?

https://github.com/jazzband/tablib/blob/57a535f577379214f415a8deee5fa2ab2c5f2415/src/tablib/formats/_tsv.py#L1-L11

Plus two lines to register the format in `formats/__init__.py` + docs + tests.

So internally, it is re-using the CSV code, which is good that this common code is reused.

I think it's better to let users explicitly import/export TSV, than require them to import/export CSV with a tab delimiter.

To go in the opposite direction, we could deprecate both the CSV and TSV formats, and retain only a generic [delimiter-separated values](https://en.wikipedia.org/wiki/Delimiter-separated_values) format requiring the delimiter to always be specified. But that won't really help people.

**Comment by claudep** [comment]
Your argumentation makes sense. Let's keep it.
