### ISSUE TITLE
Plans to support column alignment?

### ISSUE THREAD

**Issue by deeplook** [jazzband/tablib#442]
I really like https://github.com/jazzband/tablib, but am missing some column alignment feature like in https://github.com/astanin/python-tabulate for normal text output. I just wonder if this is on some roadmap? I can do without, but it would be nice. ;)

**Comment by claudep** [comment]
Absolutely, tabulate support will be in the next release!
https://github.com/jazzband/tablib/commit/fa30ea858d0ac41f2f542e0c50d9f9a2e343deb2

Happy new year!
