### ISSUE TITLE
Release tablib 1.0

### ISSUE THREAD

**Issue by claudep** [jazzband/tablib#444]
Hey @hugovk, what about a tablib release? Time for 1.0?

**Comment by hugovk** [comment]
Yes, let's go for it!

Perhaps include https://github.com/jazzband/tablib/pull/445 first?

**Comment by hugovk** [comment]
Would you like to do this one? 

The automation makes it quite easy, here's the release checklist. 

https://github.com/jazzband/tablib/blob/master/RELEASING.md

Is there anything else needed for merging before release?

**Comment by claudep** [comment]
Hopefully done right!

**Comment by hugovk** [comment]
Looks good, I can see the wheel and source here:

https://pypi.org/project/tablib/1.0.0/#files

Thanks!
