### ISSUE TITLE
Dependencies removed from this project

### ISSUE THREAD

**Issue by LuRsT** [jazzband/tablib#446]
Hi, I realised that with the new version, the dependencies were removed (I think here: https://github.com/jazzband/tablib/pull/436) that caused a problem in one of our services, easily fixed by fixing the version to `0.14.0`, but I was wondering if the point of this project is to be completely generic and not relying on anything unless the user needs to, or if you will have some requirements.

I'm talking specifically about the `odfpy` requirement, but it'd be good to know if you plan on being dependency-less, so I can amend our service the right way.

PS: We're using `tablib` through django-import-export

UPDATE: Here's others talking about the same problem: https://github.com/django-import-export/django-import-export/issues/1064

**Comment by claudep** [comment]
Yes, the idea was to not require any dependency unless you really want that format. If you want to continue having all possible formats, just depend on `tablib[all]`. Each "client" can decide which dependency they would like to have by default and which one they want to keep optional.

**Comment by LuRsT** [comment]
Alright, thanks @claudep!

**Comment by hugovk** [comment]
> I'm talking specifically about the `odfpy` requirement, but it'd be good to know if you plan on being dependency-less, so I can amend our service the right way.

And in your case you could depend on `tablib[ods]`.

Here it is in the docs:

* https://tablib.readthedocs.io/en/stable/install/

**Comment by LuRsT** [comment]
Hi @hugovk, yeah, indeed that would work for me, since this is a dependency of a dependency for us, I'll fix to the previous version and update https://github.com/django-import-export/django-import-export/ to depend on the right version (and dependencies) of `tablib`.

Thanks for your help!
