### ISSUE TITLE
tablib=1.0.0

### ISSUE THREAD

**Issue by mhmrx** [jazzband/tablib#447]
tablib in version 1.0 which is installed as dependency of django-import-export causes errors, it doesnt download its dependencies as it was in 0.14.0:

>     - markuppy [required: Any, installed: 1.14]
>     - odfpy [required: Any, installed: 1.4.0]
>       - defusedxml [required: Any, installed: 0.6.0]
>     - openpyxl [required: >=2.4.0, installed: 3.0.3]
>       - et-xmlfile [required: Any, installed: 1.0.1]
>       - jdcal [required: Any, installed: 1.4.1]
>     - pyyaml [required: Any, installed: 5.3]
>     - xlrd [required: Any, installed: 1.2.0]
>     - xlwt [required: Any, installed: 1.3.0]

dependencies  in v 1.0 look like this:

>   - diff-match-patch [required: Any, installed: 20181111]
>   - django [required: >=1.8, installed: 2.1.15]
>     - pytz [required: Any, installed: 2019.3]
>   - tablib [required: Any, installed: 1.0.0]

and then generates errors with imports like this:

`  File "/usr/local/lib/python3.6/site-packages/tablib/formats/_xlsx.py", line 6, in <module>
    import openpyxl
ModuleNotFoundError: No module named 'openpyxl'`

**Comment by hugovk** [comment]
In 1.0, you need to specify the dependencies you need.

For example, `pip install tablib[xlsx]` or `pip install tablib[all]`.

Docs:
* https://tablib.readthedocs.io/en/stable/install/#install
* https://github.com/jazzband/tablib/blob/master/HISTORY.md#100-2020-01-13

**Comment by mhmrx** [comment]
Ok. Didn't know that. It took me a lot of time to find out what is wrong :)

**Comment by claudep** [comment]
https://github.com/django-import-export/django-import-export/pull/1061 is intented to fix the problem.
