### ISSUE TITLE
show release history in docs

### ISSUE THREAD

**Issue by okke-formsma** [jazzband/tablib#468]
Hi,  

thanks for the library. It took me a while today to find the releases.md file with the breaking changes for each version. Could you please add this to the documentation and github releases pages as well? I just saw that these are published nicely on pipy :)

Thanks!

**Comment by claudep** [comment]
You mean `HISTORY.md`? Yes, sure, this is a very good suggestion.

**Comment by okke-formsma** [comment]
yes, HISTORY.md it is :duck:
