### ISSUE TITLE
zsh: no matches found: tablib[all]

### ISSUE THREAD

**Issue by erfelipe** [jazzband/tablib#473]
Dear, 
I'm try to use tablib and import the export options. But the line:
`pip install tablib[all]`
and
`pip install tablib[xlsx]`
give me the follow error:` zsh: no matches found: tablib[xlsx]`  or` zsh: no matches found: tablib[all] ` 

My setup is macOS + VsCode + Python (venv) 3.8.1 

Regards,

**Comment by hugovk** [comment]
Does it work with quotes? 

```sh
pip install "tablib[all]"
pip install "tablib[xlsx]"
```

**Comment by erfelipe** [comment]
Yeap! 
 Perhaps this kind of example could be write in documentation (readthedocs).

Thanks @hugovk  

![image](https://user-images.githubusercontent.com/17271754/90015144-93177700-dc7e-11ea-8080-bb94f3aab59f.png)

**Comment by hugovk** [comment]
> Perhaps this kind of example could be write in documentation (readthedocs).

Good idea, I've created PR 474.
