### ISSUE TITLE
"Invalid character / found in sheet title" during export to XLSX

### ISSUE THREAD

**Issue by mpasternak** [jazzband/tablib#489]
Hi there, 

it looks like tablib could automatically replace some characters when exporting to XLS, what do you think? The problem occurs when I export a sheet with a slash inside its title:

```
  File "/Users/mpasternak/.virtualenvs/bpp/lib/python3.8/site-packages/tablib/formats/_xlsx.py", line 53, in export_book
    ws.title = dset.title if dset.title else 'Sheet%s' % (i)
  File "/Users/mpasternak/.virtualenvs/bpp/lib/python3.8/site-packages/openpyxl/workbook/child.py", line 93, in title
    raise ValueError(msg)
ValueError: Invalid character / found in sheet title
```

Devs, please let me know if this is desired and I'll think about a patch.

**Comment by claudep** [comment]
Would you suggest replacing invalid chars (`INVALID_TITLE_REGEX = re.compile(r'[\\*?:/\[\]]')` with underscores?

**Comment by mpasternak** [comment]
Seems legit. Optionally make the underscore configurable with something else.

**Comment by claudep** [comment]
Feel free to suggest a patch!

**Comment by mpasternak** [comment]
OK cool, PR coming soon
