### ISSUE TITLE
Selecting name of the excel sheet while loading an excel file with tablib

### ISSUE THREAD

**Issue by andredemori** [jazzband/tablib#495]
I have an excel file to load with 4 sheets. I want to load a specific sheet from. How can I choose the name of the sheet? Is it possible with tablib? How to read a specific sheet and ignore the others?

This doesn't help. I can't choose a specific sheet.

imported_data= dataset.load(file.read( ), format= 'xlsx')

**Comment by claudep** [comment]
Use a Databook instead (https://tablib.readthedocs.io/en/stable/tutorial/#excel-workbook-with-multiple-sheets, https://tablib.readthedocs.io/en/stable/api/#databook-object).
