### ISSUE TITLE
Is the documentation site compromised?

### ISSUE THREAD

**Issue by saemideluxe** [jazzband/tablib#499]
I see the following on the documentation page (with a link to the according website, http://quickcash24.com/): 

![screenshot-1633953098_317x227](https://user-images.githubusercontent.com/3115209/136785500-ff4939d5-58ea-4611-a269-f5ef8521c04f.png)

Am I correct in assuming that this is not itentionally? No problem with ads, but I am unable use the search bar ;)

**Comment by hugovk** [comment]
Ah right, that's Kenneth's own domain we don't have access to (see https://github.com/jazzband/tablib/issues/377), and we're using RTD now.

https://lookup.icann.org/lookup shows:

```
Registry Expiration: 2022-10-22 17:33:55 UTC
Updated: 2021-10-06 05:12:31 UTC
Created: 2011-10-22 17:33:55 UTC
```

Anyway, it's out of our hands, please use https://tablib.readthedocs.io!

(If you see links on some website to the old one, we may be able to ask them to update, but not really if it's Google :)
