### ISSUE TITLE
csv file format not auto detected.

### ISSUE THREAD

**Issue by knowingpark** [jazzband/tablib#502]
I was surprised to get an error loading a csv file, the error was:

`tablib.exceptions.UnsupportedFormat: Tablib has no format 'None' or it is not registered.`

I got it to load by adding a `format='csv'` parameter to the load function.
I just thought this isn't right! So I look a bit deeper. 

All the way into the Python csv itself, which is where the problem was being created.
The csv module has a `_guess_delimiter` method which doesn't play well with the 1024 byte csv sample the `format._csv.py` was sending it. `_guess_delimiter` doesn't expect partial lines. The partial line at the end of the sample doesn't have enough columns and _guess_delimiter gives up and raises an Error. This error trips the `try`/`except` in `_csv.detect()`.

I made it work by creating a stream_sample that ends on a `'\n'`

```python
@classmethod
    def detect(cls, stream, delimiter=None):
        stream_sample = "\n".join(stream.read(1024).split("\n")[:-1])
        try:
            csv.Sniffer().sniff(
                stream_sample, delimiters=delimiter or cls.DEFAULT_DELIMITER
            )
            return True
        except Exception:
            return False
```

I'm using python 3.8, tablib 3.0.0
The problem should be probably be resolved in the csv module!
I've never made a PR, so I'm happy to let someone else resolve this, if it is decided that it is a real problem.

**Comment by knowingpark** [comment]
Cool.
Please point me to the PR instructions.
It will be my first one :)
Exciting!

**Comment by hugovk** [comment]
Great!

We have a brief guide at https://github.com/jazzband/tablib/blob/master/.github/CONTRIBUTING.md

Here's a video showing how to make your first PR:

https://hacktoberfest.digitalocean.com/resources

And another guide at:

https://guides.github.com/activities/forking/
