### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by hugovk** [jazzband/tablib#506]
Shall we make a new release?

The last release was in December 2020:

* https://github.com/jazzband/tablib/releases/tag/v3.0.0
* https://github.com/jazzband/tablib/compare/v3.0.0...master

Notable PRs merged since then:

* https://github.com/jazzband/tablib/pull/494
* https://github.com/jazzband/tablib/pull/497
* https://github.com/jazzband/tablib/pull/501
* https://github.com/jazzband/tablib/pull/503
* https://github.com/jazzband/tablib/pull/504

**Comment by dogukanteber** [comment]
Is this project still active @claudep @hugovk. I am looking for an open-source project to dedicate my time to and contribute as much as I can. There seems to be not much movement in issues and PRs. If it is still active, I have a couple of ideas to add to this project.

**Comment by claudep** [comment]
This project is maintained, however not very active regarding new features. Feel free to suggest/discuss new functionalities (create tickets for that, of course).
