### ISSUE TITLE
Add <tbody> tags to html output

### ISSUE THREAD

**Issue by krowbar** [jazzband/tablib#538]
A table exported to html with a header row no longer renders properly (on recent chrome, edge and firefox) if passed through a minifier that drops optional end tags.
The table renders styled as all header rows.

Wrapping the rows with tbody.open/tbody.close fixes the rendering problem.

` page.tbody.open()`
` for row in dataset:`
`    new_row = [item if item is not None else "" for item in row]`
`    html_row = markup.oneliner.td(new_row)`
`    page.tr(html_row)`
`page.tbody.close()`

In the case I noticed, the table was 12K minified, but 19K minified if the end tags were included -- about a hundred rows and 9 columns.

**Comment by krowbar** [comment]
[tablib_html.patch](https://github.com/jazzband/tablib/files/10746830/tablib_html.patch)

Let me know if you want something different.

**Comment by claudep** [comment]
Ideally if you could make it a pull request, would be nice! Tell us if you need any help.

**Comment by krowbar** [comment]
Pull request submitted.

**Comment by krowbar** [comment]
Updated the html test generation in my version.
