### ISSUE TITLE
Can't update a field

### ISSUE THREAD

**Issue by harmv** [jazzband/tablib#54]
Updating a field fails silently.
It should either work, or fail loudly 
## how to reproduce

``` python
import tablib

headers = ('h1', 'h2')
data = tablib.Dataset(headers=headers)
data.append(('foo', 'bar'))
data.append(('foo2', 'bar2'))

data['h1'][1] = 'new'   # update a single cell
assert data['h1'][1] == 'new', "error still contains %s" % data['h1'][1]
```
## result

The update does not barf, but doesn't work either.

> Traceback (most recent call last):
> File "test.py", line 10, in <module>
>    assert data['h1'][1] == 'new', "error still contains %s" % data['h1'][1]
> AssertionError: error still contains foo2'''
## expected result

cell is updated or tablib refuses the assignment.

**Comment by jleclanche** [comment]
Would love to see a Dataset.update() API of sorts.
