### ISSUE TITLE
Please make markuppy test dependency optional

### ISSUE THREAD

**Issue by mgorny** [jazzband/tablib#553]
We'd like to package tablib for Gentoo and run its test suite. However, it depends on MarkupPy right now, and this package is not really a good fit (last release in 2017, no tests, broken GitHub repository). Could you please consider making this test dependency optional?

**Comment by claudep** [comment]
#554 *could* be a way to avoid MarkupPy dependency. Opinions welcome.

**Comment by claudep** [comment]
markkuppy is no longer a dependency, see f3ef2e94b404
