### ISSUE TITLE
appending rows when there are dynamic columns 

### ISSUE THREAD

**Issue by LucOevel** [jazzband/tablib#572]
At the moment we cannot add rows (using append, rpush, lpush) when there is already a dynamic column: a function object can be added at the appropriate place in the row, but unlike a normal dynamic column it will not be executed.

**Comment by claudep** [comment]
Thanks for the report, are you planning a pull request?

**Comment by LucOevel** [comment]
no... (I would if i could)

**Comment by claudep** [comment]
It would be great if you could test (or make test) the suggested patch above.

**Comment by LucOevel** [comment]
#----short test

import tablib
data = tablib.Dataset()

txt='''Greg Thorton
Dave Coutts
Joshua Ourisman'''

data.extend([item.split() for item in txt.splitlines()])

def dynamicColumn(row):
    return row[-1].upper()+'!'

data.append_col(dynamicColumn,'Calculated')  #after this cannot add rows anymore

data.append(('Brad','Montgomery', dynamicColumn))

print(tablib.__version__)
print(data)

    #----------result: as before, dynamicColumn is not evaluated:
    #3.5
    # Greg  |Thorton   |THORTON!
    # Dave  |Coutts    |COUTTS!
    # Joshua|Ourisman  |OURISMAN!
    # Brad  |Montgomery|<function dynamicColumn at 0x000001A071042940>

**Comment by LucOevel** [comment]
#correction:
print(tablib.__version__)
3.5.0

**Comment by LucOevel** [comment]
```
    print(tablib.__version__)
    
    data = tablib.Dataset()

    txt='''Greg Thorton
Dave Coutts
Joshua Ourisman'''

    data.extend([item.split() for item in txt.splitlines()])

    def dynamicColumn(row):
        return row[-1].upper()+'!'


    data.append_col(dynamicColumn,'Calculated')  #after this cannot add rows anymore

    data.append(('Brad','Montgomery', dynamicColumn))

    #----------result: as before, dynamicColumn is not evaluated:
    #3.5.0
    # Greg  |Thorton   |THORTON!
    # Dave  |Coutts    |COUTTS!
    # Joshua|Ourisman  |OURISMAN!
    # Brad  |Montgomery|<function dynamicColumn at 0x000001A071042940>
```

**Comment by claudep** [comment]
@hugovk do you think that adding dynamic values in rows is worth implementing? We could argue that when inserting rows, you should be able to compute the values yourself.

**Comment by hugovk** [comment]
I don't need it and am generally for less maintenance but not against it :)

**Comment by claudep** [comment]
@LucOevel, I committed the current patch which matches this issue description. Now feel free to create a new ticket for adding support to appending rows including callable values. However, please describe also the use case for that functionality, as you could as well prepare the values you are going to insert before adding the row.

**Comment by LucOevel** [comment]
As I understood it, the main point of dynamic columns is that their content automatically depends on other columns.  So when other columns change, the dynamic values follow dynamically.  Is that not what the name means?   Having to pre-compute values when inserting a new row defeats that behavior, and those values will not be dynamic anymore.    If the idea is that values can just as well be pre-computed instead of dynamic then why have dynamic values at all, right?   
Why have dynamic elements when adding columns but not  when adding rows?
