### ISSUE TITLE
possible bug/typo in core.py L418 (Dataset.load): reference to global `import_set`

### ISSUE THREAD

**Issue by AmitAronovitch** [jazzband/tablib#603]
The current code of Dataset.load()  has:
```python
    def load(self, in_stream, format=None, **kwargs):
        ...
        if not import_set:
            raise UnsupportedFormat(f'Format {format} cannot be imported.')
```

I am not sure what is the purpose of this condition (maybe remainder from older code, or maybe should be `fmt.import_set`), but as it is now, since there is no local variable of that name, it actually refers to the module-level function `import_set`.

  This means that the condition checked here will never occur (unless the module's namespace is overwritten in runtime), and it is redundant.

**Comment by claudep** [comment]
Hi Amit,

You are totally right, those two lines should be simply removed IMO. Could you please suggest a patch with this correction?
